# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    guzzle_config:
        base_uri: https://api.github.com
        exceptions: false
        headers:
            Accept: application/json

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    guzzle_service:
        class: GuzzleHttp\Client
        arguments: ['%guzzle_config%']

    GuzzleHttp\ClientInterface: '@guzzle_service'

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
